### ISSUE TITLE
small date fixes

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/gameon#83] opened 2012-12-05 01:51 UTC
due to delaying a week we need to extend the deadline a few days.

Now read :  closes February 24

Also on the front page it says Submissions open
November 21, 2012 and close February 20, 2013. 

Should be
Submissions open whatever date we launch, i.e. Dec 11

**Comment by rossbruniges** [comment] 2012-12-05 08:57
Closing this is really it's not a bug - we need people to test the submission flow which means on dev we need the challenge to be open in the database, this then gets reflected in the site copy.

The challenge opening and closing dates can be changed to whatever you want in the admin when the site is live.

**Closed as completed by rossbruniges** 2012-12-05 08:57 UTC
Labels: invalid
